### ISSUE TITLE
[Bug]: Partners Brand Logos are not visible in light theme 

### ISSUE THREAD

**Issue by vaibhav-xt** [layer5io/layer5#4375]
### Description

  I found in [Partners Page](https://layer5.io/partners) brand logos are not visible in light also few logos are not visible in dark mode. 

### Expected Behavior

The expected behavior is that brand logos should be visible in both light and dark themes. 

### Screenshots

![Screenshot (53)](https://github.com/layer5io/layer5/assets/90946899/e268b9d5-5858-4db7-98a5-e7318c2eb968)
![Screenshot (54)](https://github.com/layer5io/layer5/assets/90946899/7a498f0c-8747-42d9-929e-fb71a4595234)

### Environment:
- Host OS: Windows
- Browser: Edge, Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vaibhav-xt** [comment]
I would like to work on this issue. Assign it to me.

**Comment by HetviSoni** [comment]
Hey @vaibhav-xt , thank you for raising the issue. But this issue was already raised before and is solved by the pr https://github.com/layer5io/layer5/pull/4296 .

**Comment by vaibhav-xt** [comment]
@HetviSoni I am not able to reflect on changes  to the website that I made in code. I have to run to the site again and again

**Comment by HetviSoni** [comment]
Are you talking about the changes on your local system not being reflected on localhost?

**Comment by vaibhav-xt** [comment]
I tried but I didn't get the answer. I raised an issue on the discussion forum

**Comment by vaibhav-xt** [comment]
@HetviSoni I saw this is not fixed yet. On the light theme, it's not visible. Look at partners page

**Comment by DarrenDsouza7273** [comment]
Hi @vaibhav-xt did you try reaching out regarding this issue on our slack channel, Please do mention the same in the discussion forum this way someone will definitely reach out to you and answer your query

**Comment by DarrenDsouza7273** [comment]
@vaibhav-xt assigned it to you please go ahead and work on it, If you have any queries you can post them on our slack channel or add the same to the discussion forum

**Comment by HetviSoni** [comment]
> @HetviSoni I saw this is not fixed yet. On the light theme, it's not visible. Look at partners page

Its not visible right now as the pr has not been merged yet. So it would be solved when the pr is merged. You can see preview of that pr for your reference https://64875e7a9f501a07ff06b177--layer5.netlify.app/partners

**Comment by vaibhav-xt** [comment]
Ok, then it's good 😊

**Comment by Savio629** [comment]
@HetviSoni Thanks for pointing it👍
